# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [5]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hrksng/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hrksng/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hrksng/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hrksng/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hrksng/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hrksng/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hrksng/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hrksng/anaconda3/include']


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [12]:
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [16]:
%run `python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [18]:
z = np.zeros(10)
z[4] = 1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [22]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [23]:
z[::-1]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [24]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [25]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [27]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [32]:
np.random.random((3,3,3))

array([[[ 0.46139261,  0.7477009 ,  0.01500535],
        [ 0.80188294,  0.34315365,  0.04900657],
        [ 0.01528756,  0.65343416,  0.25844669]],

       [[ 0.67759958,  0.36792597,  0.77837832],
        [ 0.47870823,  0.486892  ,  0.74635598],
        [ 0.06784608,  0.09525642,  0.36069508]],

       [[ 0.24144766,  0.0330734 ,  0.07712627],
        [ 0.90575967,  0.21622322,  0.99416641],
        [ 0.00509035,  0.90621671,  0.81149327]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [35]:
z = np.random.random((10,10))
print(z)
print(np.min(z))
print(np.max(z))
print(z.min())
print(z.max())

[[ 0.53166321  0.44119556  0.64755964  0.03649331  0.9251536   0.40006832
   0.10664103  0.63814615  0.62338373  0.98043181]
 [ 0.93140586  0.23147409  0.32342936  0.32694777  0.94531609  0.26173755
   0.05263493  0.18467581  0.09382983  0.55919102]
 [ 0.85781503  0.64979951  0.30412432  0.60281782  0.16629745  0.99209768
   0.66766168  0.36293732  0.08056501  0.87673327]
 [ 0.68051641  0.48376772  0.51527678  0.70464482  0.09279636  0.91929672
   0.21332569  0.78459692  0.20107775  0.39688142]
 [ 0.71166871  0.31518146  0.83565202  0.62899325  0.77859388  0.3128566
   0.16502839  0.62513265  0.87638678  0.06209445]
 [ 0.76896066  0.27321161  0.28719641  0.60727019  0.15370642  0.47710416
   0.38923884  0.50465894  0.72736801  0.34393691]
 [ 0.89435061  0.93008359  0.10656244  0.38879684  0.27057071  0.23043353
   0.76773107  0.15283902  0.75543758  0.88133988]
 [ 0.68740866  0.91458601  0.32753514  0.3702062   0.64165509  0.42940625
   0.58261661  0.68475461  0.55622257  0.02331839]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [38]:
z = np.random.random(30)
print(z)
print(z.mean())

[ 0.6994874   0.058111    0.5428437   0.85061041  0.21809777  0.52358251
  0.46155677  0.75274867  0.95616169  0.7817509   0.72880011  0.03639383
  0.64646276  0.27013517  0.16698286  0.13954319  0.86349148  0.64268822
  0.49737456  0.99225556  0.58006162  0.60538493  0.22713238  0.70577107
  0.33089513  0.38518647  0.98409595  0.00436103  0.27514915  0.30791868]
0.507834499569


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [41]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [44]:
a = np.pad(z, pad_width=2, mode="constant", constant_values=0)
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [46]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [50]:
np.diag(1 + np.arange(0,4), k = -2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [89]:
z = np.zeros((8,8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [91]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [98]:
np.tile(np.array([[0,1],[1,0]]), (2,2))

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [102]:
x = np.random.random((5,5))
print(x)
print((x - np.min(z))/(np.max(x) - np.min(z)))

[[ 0.27585104  0.32524172  0.0582627   0.50535676  0.75211713]
 [ 0.59328064  0.05298821  0.18567767  0.43839482  0.71673271]
 [ 0.9253227   0.42565813  0.83395676  0.1296333   0.23467233]
 [ 0.83448789  0.04128411  0.93305574  0.02954872  0.50017525]
 [ 0.92287564  0.05733647  0.02825929  0.69845123  0.30386772]]
[[ 0.29564262  0.34857695  0.06244289  0.54161476  0.80607953]
 [ 0.63584694  0.05678998  0.19899954  0.46984848  0.76815637]
 [ 0.99171214  0.45619796  0.89379093  0.13893415  0.25150944]
 [ 0.89436016  0.04424613  1.          0.03166876  0.53606148]
 [ 0.98908951  0.06145021  0.03028682  0.74856324  0.32566941]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [105]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [108]:
print(np.dot(np.ones((5,3)), np.ones((3,2))))

print(np.ones((5,3)) @ np.ones((3,2)))

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]
[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [117]:
z = np.arange(11)
print(z)
z[(3 < z) & (z <= 8)] *= -1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [120]:
print(sum(range(5), -1))

9
range(0, 5)


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [125]:
print(np.array(0) / (np.array(0)))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/Users/hrksng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/hrksng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [126]:
z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(z)), z))

[ -7.   4.   1.  10.   5.  -1.  -1.   2.  -2.  -7.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [132]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0, 10, 10)
print(z1)
print(z2)
print(np.intersect1d(z1, z2))

[1 3 4 6 7 8 4 2 9 1]
[0 7 3 6 1 7 0 8 9 9]
[1 3 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [135]:
defaults = np.seterr(all="ignore")
z = np.ones(1)/0

_ = np.seterr(**defaults)

An equivalent way, with a context manager:
    z = np.ones(1)/0

SyntaxError: invalid syntax (<ipython-input-135-e7bae7f7aa3b>, line 6)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [136]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/hrksng/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [137]:
print(np.datetime64("today", "D") - np.timedelta64(1, "D"))
print(np.datetime64("today", "D"))
print(np.datetime64("today", "D") + np.timedelta64(1, "D"))

2018-01-05
2018-01-06
2018-01-07


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [141]:
np.arange("2016-07", "2016-08", dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [145]:
a = np.ones(3)
b = np.ones(3)*2
c = np.ones(3)*3
print(a)
print(np.multiply(np.add(a,b),np.divide(-a,2)))

[ 1.  1.  1.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [152]:
z = np.random.uniform(0, 10, 10)
print(z)
print(z - z%1)
print(np.floor(z))
print(np.ceil(z))
print(z.astype(int))
print(np.trunc(z))

[ 0.18049747  4.61043962  8.38568129  1.87493398  2.63662115  9.52447514
  8.69014546  2.81162403  9.66200331  2.94079773]
[ 0.  4.  8.  1.  2.  9.  8.  2.  9.  2.]
[ 0.  4.  8.  1.  2.  9.  8.  2.  9.  2.]
[  1.   5.   9.   2.   3.  10.   9.   3.  10.   3.]
[0 4 8 1 2 9 8 2 9 2]
[ 0.  4.  8.  1.  2.  9.  8.  2.  9.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange


In [159]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [160]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=float, count=-1)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [161]:
np.linspace(0, 1,11,endpoint=False)[1:]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [169]:
z = np.random.random(10)
z.sort()
print(z)

[ 0.03457189  0.05679685  0.06743091  0.13388745  0.49701393  0.58174263
  0.67139735  0.86163292  0.90350171  0.90573635]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [170]:
z = np.arange(10)
print(np.add.reduce(z))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [174]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.allclose(a, b)
print(equal)

arr_equal = np.array_equal(a,b)
print(arr_equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [182]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [186]:
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[ 1.06612041  1.15376908  0.99136773  0.67358813  1.03219962  1.02874041
  0.81721296  0.75007224  0.52359828  1.34845821]
[ 0.51937094  0.98275286  0.06086455  0.41249576  0.25665345  0.82235951
  0.27056318  1.28316534  0.63836286  0.75168802]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [189]:
z = np.random.random(10)
print(z)
z[z.argmax()] = 0
print(z)

[ 0.53258527  0.78869068  0.96433305  0.46345725  0.66068403  0.58327933
  0.18224546  0.75509041  0.591685    0.17586302]
[ 0.53258527  0.78869068  0.          0.46345725  0.66068403  0.58327933
  0.18224546  0.75509041  0.591685    0.17586302]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [190]:
z = np.zeros((5,5), [("x", float), ("y", float)])
z["x"], z["y"] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [197]:
x = np.arange(8)
y = x + 0.5
print(x)
print(y)
c = 1/np.subtract.outer(x , y)
print(c)

[0 1 2 3 4 5 6 7]
[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [198]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [199]:
np.set_printoptions(threshold=np.nan)
z = np.zeros((10,10))
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [202]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z - v)).argmin()
print(np.abs(z-v))
print(z[index])

[  6.30370259e+01   6.20370259e+01   6.10370259e+01   6.00370259e+01
   5.90370259e+01   5.80370259e+01   5.70370259e+01   5.60370259e+01
   5.50370259e+01   5.40370259e+01   5.30370259e+01   5.20370259e+01
   5.10370259e+01   5.00370259e+01   4.90370259e+01   4.80370259e+01
   4.70370259e+01   4.60370259e+01   4.50370259e+01   4.40370259e+01
   4.30370259e+01   4.20370259e+01   4.10370259e+01   4.00370259e+01
   3.90370259e+01   3.80370259e+01   3.70370259e+01   3.60370259e+01
   3.50370259e+01   3.40370259e+01   3.30370259e+01   3.20370259e+01
   3.10370259e+01   3.00370259e+01   2.90370259e+01   2.80370259e+01
   2.70370259e+01   2.60370259e+01   2.50370259e+01   2.40370259e+01
   2.30370259e+01   2.20370259e+01   2.10370259e+01   2.00370259e+01
   1.90370259e+01   1.80370259e+01   1.70370259e+01   1.60370259e+01
   1.50370259e+01   1.40370259e+01   1.30370259e+01   1.20370259e+01
   1.10370259e+01   1.00370259e+01   9.03702590e+00   8.03702590e+00
   7.03702590e+00   6.03702590e+00

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [203]:
z = np.zeros (10, [("position", [("x", float, 1),
                                ("y", float, 1)]),
                  ("color", [("r", float, 1),
                            ("g", float, 1),
                            ("b", float, 1)])])
print(z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [204]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0],z[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

import scipy.spatial

z = np.random.random((10,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[ 0.          0.58820694  0.17494992  0.94005353  0.2266632   0.24537586
   0.81400653  0.46368706  0.57194515  0.71289378]
 [ 0.58820694  0.          0.47395224  0.82169606  0.80299681  0.38825305
   1.15618085  0.15206371  0.9842093   0.86471006]
 [ 0.17494992  0.47395224  0.          0.77498687  0.34116032  0.08805139
   0.76473949  0.33055864  0.54898975  0.59040388]
 [ 0.94005353  0.82169606  0.77498687  0.          0.99797211  0.74386446
   0.7518744   0.73625636  0.7822113   0.39537281]
 [ 0.2266632   0.80299681  0.34116032  0.99797211  0.          0.42851938
   0.68369704  0.66758503  0.43128143  0.69152322]
 [ 0.24537586  0.38825305  0.08805139  0.74386446  0.42851938  0.
   0.81804985  0.2429035   0.61564897  0.60623549]
 [ 0.81400653  1.15618085  0.76473949  0.7518744   0.68369704  0.81804985
   0.          1.00726423  0.25243357  0.37392521]
 [ 0.46368706  0.15206371  0.33055864  0.73625636  0.66758503  0.2429035
   1.00726423  0.          0.83217032  0.72886342]
 [ 0.5719

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [205]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print(z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [206]:
from io import StringIO

s = StringIO("""1,2,3,4,5\n
                    6, ,  ,7, 8\n
                    , , 9, 10,11\n""")
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

TypeError: must be str or None, not bytes

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [208]:
z = np.arange(9).reshape(3,3)
print(z)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [210]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1, 1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / (2.0 * sigma**2)))
print(g)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [213]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [220]:
x = np.random.rand(5,10)
print(x)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1,1)
print(y)

[[ 0.82593273  0.69877227  0.76635072  0.75915805  0.3764329   0.82439231
   0.57428484  0.16493843  0.25716053  0.39730808]
 [ 0.19866615  0.18387644  0.11164005  0.01815185  0.45316445  0.17186601
   0.56106988  0.79821525  0.70434618  0.44414469]
 [ 0.19057933  0.11365508  0.15605128  0.64493026  0.0185911   0.62377305
   0.42300932  0.56154064  0.87591267  0.74598862]
 [ 0.24387669  0.99437645  0.40158251  0.15460883  0.77397973  0.71902191
   0.47095282  0.6792498   0.07971499  0.17855852]
 [ 0.73718514  0.80128509  0.17416661  0.38188622  0.88295852  0.8145435
   0.36484842  0.10278733  0.60352207  0.97541597]]
[[ 0.26145965  0.13429919  0.20187763  0.19468497 -0.18804019  0.25991922
   0.00981176 -0.39953465 -0.30731256 -0.16716501]
 [-0.16584794 -0.18063766 -0.25287404 -0.34636225  0.08865035 -0.19264808
   0.19655579  0.43370115  0.33983208  0.0796306 ]
 [-0.2448238  -0.32174806 -0.27935185  0.20952713 -0.41681204  0.18836992
  -0.01239382  0.12613751  0.44050953  0.31058549]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [221]:
z = np.random.randint(0, 10, (3,3))
print(z)
print(z[z[:,1].argsort()])

[[9 4 9]
 [0 4 6]
 [9 8 7]]
[[9 4 9]
 [0 4 6]
 [9 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [222]:
z = np.random.randint(0, 3, (3,10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [225]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5210944837


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [226]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [227]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, "name", "no name")
        
z = NamedArray(np.arange(10), "range_10")
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [228]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
z += np.bincount(i, minlength=len(z))
print(z)

np.add.at(z,i,1)
print(z)

[ 6.  2.  4.  2.  2.  2.  2.  2.  5.  3.]
[ 11.   3.   7.   3.   3.   3.   3.   3.   9.   5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [229]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f = np.bincount(i,x)
print(f)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [230]:
w, h = 16, 16
i = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)

f = i[...,0]*(256*256)+i[...,1]*256 + i[...,2]
n = len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [233]:
A = np.random.randint(0,10,(3,4,3,4))
# print(A)
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[56 50 60 54]
 [60 60 44 60]
 [74 50 54 46]]
[[56 50 60 54]
 [60 60 44 60]
 [74 50 54 46]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [236]:
d = np.random.uniform(0, 1, 100)
s = np.random.randint(0, 10, 100)
d_sums = np.bincount(s, weights=d)
d_counts = np.bincount(s)
d_means = d_sums / d_counts
print(d_means)

import pandas as pd
print(pd.Series(d).groupby(s).mean())

[ 0.42792668  0.70525048  0.28973787  0.38171079  0.32809738  0.55054838
  0.49215022  0.58719382  0.51247319  0.36759648]
0    0.427927
1    0.705250
2    0.289738
3    0.381711
4    0.328097
5    0.550548
6    0.492150
7    0.587194
8    0.512473
9    0.367596
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [237]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))

np.diag(np.dot(a,b))

np.sum(a * b.T, axis=1)

np.einsum("ij,ji->i", a,b)

array([ 1.37645968,  1.79374896,  1.07674607,  1.20057493,  1.6840806 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [238]:
z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(z) + (len(z)-1)*(nz))
z0[::nz+1] = z
print(z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [239]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [242]:
a = np.arange(25).reshape(5,5)
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [245]:
faces = np.random.randint(0,100,(10,3))
print(faces)
f = np.roll(faces.repeat(2, axis=1), -1, axis=1)
print(f)
f = f.reshape(len(f)*3, 2)
print(f)
f = np.sort(f, axis=1)
print(f)
g = f.view(dtype=[("p0", f.dtype),("p1", f.dtype)])
print(g)
g = np.unique(g)
print(g)

[[11 91 55]
 [77 63 39]
 [92 82 77]
 [20 25 97]
 [94 75 94]
 [78 24 85]
 [42 13 75]
 [46 52 40]
 [22 42  0]
 [ 8 46 98]]
[[11 91 91 55 55 11]
 [77 63 63 39 39 77]
 [92 82 82 77 77 92]
 [20 25 25 97 97 20]
 [94 75 75 94 94 94]
 [78 24 24 85 85 78]
 [42 13 13 75 75 42]
 [46 52 52 40 40 46]
 [22 42 42  0  0 22]
 [ 8 46 46 98 98  8]]
[[11 91]
 [91 55]
 [55 11]
 [77 63]
 [63 39]
 [39 77]
 [92 82]
 [82 77]
 [77 92]
 [20 25]
 [25 97]
 [97 20]
 [94 75]
 [75 94]
 [94 94]
 [78 24]
 [24 85]
 [85 78]
 [42 13]
 [13 75]
 [75 42]
 [46 52]
 [52 40]
 [40 46]
 [22 42]
 [42  0]
 [ 0 22]
 [ 8 46]
 [46 98]
 [98  8]]
[[11 91]
 [55 91]
 [11 55]
 [63 77]
 [39 63]
 [39 77]
 [82 92]
 [77 82]
 [77 92]
 [20 25]
 [25 97]
 [20 97]
 [75 94]
 [75 94]
 [94 94]
 [24 78]
 [24 85]
 [78 85]
 [13 42]
 [13 75]
 [42 75]
 [46 52]
 [40 52]
 [40 46]
 [22 42]
 [ 0 42]
 [ 0 22]
 [ 8 46]
 [46 98]
 [ 8 98]]
[[(11, 91)]
 [(55, 91)]
 [(11, 55)]
 [(63, 77)]
 [(39, 63)]
 [(39, 77)]
 [(82, 92)]
 [(77, 82)]
 [(77, 92)]
 [(20, 25)]
 [(25,

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [248]:
c = np.bincount([1,1,2,3,4,4,6])
print(c)
print(np.arange(7))
a = np.repeat(np.arange(len(c)), c)
print(a)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [249]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
z = np.arange(20)
print(moving_average(z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [250]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z = rolling(np.arange(10),3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [251]:
z = np.random.randint(0,2,100)
np.logical_not(z, out=z)

z = np.random.uniform(-1.0, 1.0, 100)
np.negative(z, out=z)

array([ 0.98290724, -0.71916241,  0.76384206,  0.34205917, -0.99341733,
        0.74109191, -0.0518137 , -0.23225505,  0.74397993, -0.02424939,
        0.37511532, -0.0885231 , -0.77903266, -0.30168282, -0.60285408,
        0.85543589,  0.13278171, -0.74062457,  0.43463403,  0.76752052,
        0.18858043, -0.62396922,  0.03442608,  0.529947  , -0.1166649 ,
       -0.82555365,  0.75123606,  0.53500364,  0.59403439,  0.16716455,
        0.77990683,  0.92383582, -0.4210752 ,  0.55415568, -0.84840239,
        0.62879257,  0.26122755,  0.72956421,  0.70344983, -0.7431127 ,
        0.76004059, -0.29638197, -0.80275928,  0.96142117, -0.06524203,
       -0.85036498,  0.57969266, -0.90383828,  0.73254455,  0.44324321,
        0.09228652,  0.9950276 ,  0.52072601,  0.07965226, -0.02914841,
        0.89574509, -0.92424284,  0.70438113,  0.18537734, -0.63751089,
        0.19964402, -0.96025703,  0.11998638, -0.76021057,  0.99985495,
       -0.38209474,  0.02997142, -0.22413899,  0.15613573, -0.09

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [256]:
def distance(p0, p1, p):
    t = p1 - p0
    l = (t**2).sum(axis=1)
    u = -((p0[:,0]-p[...,0])*t[:,0] + (p0[:,1]-p[...,1])*t[:,1])/l
    u = u.reshape(len(u),1)
    d = p0 + u*t - p
    return np.sqrt((d**2).sum(axis=1))

p0 = np.random.uniform(-10,10, (10,2))
p1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform()

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [257]:
p0 = np.random.uniform(-10,10, (10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[  7.22790843   4.80575393   6.4715402    4.26794299   8.0867668
    7.58684674   0.35364316   9.14333394   1.71324749   2.96495838]
 [  1.04782099  12.49418587  12.77738463   9.31260896   0.24512784
   13.50385288   5.97828564   1.44405669   2.88535995   5.25299601]
 [  1.29441674   0.08998106   4.56166833  10.24120748   5.4238513
    4.65435733  12.70860991   2.0148256   17.19637767   3.92860737]
 [  0.62640314   3.29988148   0.69895789   6.274559     2.97932954
    0.73857599   8.7663796    2.93224719  13.23236172   5.68154626]
 [  0.89499199   4.13522499   0.38116362   5.09062223   2.52256923
    0.38122559   7.62165268   2.86479809  12.02608246   5.89189144]
 [  4.76158745  14.85065889  13.97262786   9.67164511   3.63617817
   14.42695745   6.70593852   2.60349116   2.97548238   9.04607813]
 [  4.89299789   1.15103484   3.89314064   8.46038728   8.32090044
    3.61300551  11.40606204   2.56930675  15.07815904   0.1355549 ]
 [ 11.36320456   1.47842219   0.32936215   2.50623131  13

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [259]:
z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

r = np.ones(shape, dtype=z.dtype)*fill
p = np.array(list(position)).astype(int)
rs = np.array(list(r.shape)).astype(int)
zs = np.array(list(z.shape)).astype(int)

r_start = np.zeros((len(shape),)).astype(int)
r_stop = np.array(list(shape)).astype(int)
z_start = (p-rs//2)
z_stop = (p + rs//2)+rs%2

r_start = (r_start - np.minimum(z_start,0)).tolist()
z_start = (np.maximum(z_start,0)).tolist()
r_stop = np.maximum(r_start,(r_stop - np.maximum(z_stop-zs,0))).tolist()
z_stop = (np.minimum(z_stop,zs)).tolist()

r2 = [slice(start,stop) for start, stop in zip(r_start, r_stop)]
z2 = [slice(start,stop) for start, stop in zip(z_start, z_stop)]
r[r2] = z[z2] 
print(z)
print(r)

[[7 2 4 6 7 5 1 3 9 5]
 [7 1 1 2 3 0 8 1 7 7]
 [8 0 4 8 0 2 7 1 4 6]
 [4 2 0 1 0 9 4 5 8 5]
 [1 1 6 9 4 9 2 5 7 0]
 [3 5 4 7 9 7 4 7 8 5]
 [4 5 4 3 7 0 8 7 2 6]
 [4 4 4 1 7 7 8 5 7 7]
 [1 4 4 4 7 0 4 3 1 5]
 [0 7 2 7 2 9 6 4 9 7]]
[[0 0 0 0 0]
 [0 7 2 4 6]
 [0 7 1 1 2]
 [0 8 0 4 8]
 [0 4 2 0 1]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [260]:
z = np.arange(1,15,dtype=np.unit32)
r = stride_tricks.as_strided(z,(11,4),(4,4))
print(r)

AttributeError: module 'numpy' has no attribute 'unit32'

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [261]:
z = np.random.uniform(0,1,(10,10))
u,s,v = np.linalg.svd(z)
rank = np.sum(s > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [262]:
z = np.random.randint(0,10,50)
print(np.bincount(z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [263]:
z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (z.shape[0] - 3)
j = 1 + (z.shape[1] - 3)
c = stride_tricks.as_strided(z, shape=(i,j,n,n),strides=z.strides + z.strides)
print(c)

[[[[0 1 3]
   [4 3 1]
   [1 0 2]]

  [[1 3 1]
   [3 1 1]
   [0 2 2]]

  [[3 1 4]
   [1 1 2]
   [2 2 4]]

  [[1 4 2]
   [1 2 4]
   [2 4 2]]

  [[4 2 2]
   [2 4 4]
   [4 2 2]]

  [[2 2 4]
   [4 4 0]
   [2 2 0]]

  [[2 4 0]
   [4 0 0]
   [2 0 4]]

  [[4 0 3]
   [0 0 4]
   [0 4 0]]]


 [[[4 3 1]
   [1 0 2]
   [0 3 0]]

  [[3 1 1]
   [0 2 2]
   [3 0 1]]

  [[1 1 2]
   [2 2 4]
   [0 1 4]]

  [[1 2 4]
   [2 4 2]
   [1 4 1]]

  [[2 4 4]
   [4 2 2]
   [4 1 1]]

  [[4 4 0]
   [2 2 0]
   [1 1 3]]

  [[4 0 0]
   [2 0 4]
   [1 3 4]]

  [[0 0 4]
   [0 4 0]
   [3 4 4]]]


 [[[1 0 2]
   [0 3 0]
   [4 2 0]]

  [[0 2 2]
   [3 0 1]
   [2 0 3]]

  [[2 2 4]
   [0 1 4]
   [0 3 1]]

  [[2 4 2]
   [1 4 1]
   [3 1 0]]

  [[4 2 2]
   [4 1 1]
   [1 0 2]]

  [[2 2 0]
   [1 1 3]
   [0 2 2]]

  [[2 0 4]
   [1 3 4]
   [2 2 3]]

  [[0 4 0]
   [3 4 4]
   [2 3 3]]]


 [[[0 3 0]
   [4 2 0]
   [4 3 3]]

  [[3 0 1]
   [2 0 3]
   [3 3 3]]

  [[0 1 4]
   [0 3 1]
   [3 3 0]]

  [[1 4 1]
   [3 1 0]
   [3 0 1]]

  [[4 1 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [265]:
class Symetric(np.ndarray):
    def __setitem__(self,index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
        
def symetric(z):
    return np.asarray(z + z.T - np.diag(z.diagonal())).view(Symetric)

s = symetric(np.random.randint(0,10,(5,5)))
s[2,3] = 42
print(s)

[[ 2 11 11 12 14]
 [11  6 13 10 11]
 [11 13  1 42  2]
 [12 10 42  0 18]
 [14 11  2 18  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [266]:
p, n = 10, 20
m = np.ones((p,n,n))
v = np.ones((p,n,1))
s = np.tensordot(m, v, axes=[[0,2],[0,1]])
print(s)

[[ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [267]:
z = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0),
                   np.arange(0, z.shape[1],k), axis=1)
print(s)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [270]:
def iterate(z):
    N = (z[0:-2,0:-2] + z[0:-2, 1:-1] + z[0:-2,2:] +
        z[1:-1, 0:-2] + z[1:-1,2:] +
        z[2:, 0:-2] + z[2:, 1:-1] + z[2:, 2:])
    
    birth = (N==3) & (z[1:-1, 1:-1]==0)
    survive = ((N==2) | (N==3)) & (z[1:-1, 1:-1]==1)
    z[...] = 0
    z[1:-1,1:-1][birth | survive] = 1
    return z

z = np.random.randint(0,2,(50,50))
for i in range(100): z = iterate(z)
print(z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [271]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5

print(z[np.argsort(z)[-n:]])

print(z[np.argpartition(-z, n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9998 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [273]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:,n] = arrays[n][ix[:,n]]
    
    return ix

print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [274]:
z = np.array([("Hello", 2.5,3),
             ("World", 3.6,2)])
r = np.core.records.fromarrays(z.T,
                              names="col1, col2, col3",
                              formats="S8, f8, i8")
print(r)

[(b'Hello',  2.5, 3) (b'World',  3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [275]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum("i,i,i->i", x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [277]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[2 3 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [278]:
z = np.random.randint(0,5,(10,3))
print(z)

e = np.all(z[:,1:] == z[:,:-1], axis=1)
u = z[~e]

print(u)

u = z[z.max(axis=1) != z.min(axis=1),:]
print(u)

[[3 3 1]
 [0 2 1]
 [2 2 2]
 [0 3 2]
 [4 2 0]
 [4 4 1]
 [2 0 3]
 [2 2 3]
 [2 1 0]
 [1 3 3]]
[[3 3 1]
 [0 2 1]
 [0 3 2]
 [4 2 0]
 [4 4 1]
 [2 0 3]
 [2 2 3]
 [2 1 0]
 [1 3 3]]
[[3 3 1]
 [0 2 1]
 [0 3 2]
 [4 2 0]
 [4 4 1]
 [2 0 3]
 [2 2 3]
 [2 1 0]
 [1 3 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [280]:
i = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
b = ((i.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(b[:,::-1])

i = np.array([0,1,2,3,15,16,32,64,128], dtype=np.unit8)
print(np.unpackbits(i[:,np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


AttributeError: module 'numpy' has no attribute 'unit8'

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [281]:
z = np.random.randint(0,2,(6,3))
t = np.ascontiguousarray(z).view(np.dtype((np.void, z.dtype.itemsize * z.shape[1])))
_, idx = np.unique(t, return_index = True)
uz = z[idx]
print(uz)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [283]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum("i->", a)
np.einsum("i,i->i", a, b)
np.einsum("i,i", a,b)
np.einsum("i,j->ij",a,b)

array([[ 0.08758999,  0.27758915,  0.33982898,  0.01091727,  0.27339792,
         0.35377836,  0.33584451,  0.2386418 ,  0.30052674,  0.23203219],
       [ 0.02973118,  0.0942237 ,  0.11535013,  0.00370571,  0.09280105,
         0.12008505,  0.11399766,  0.08100357,  0.10200954,  0.07876004],
       [ 0.01032328,  0.03271642,  0.04005196,  0.0012867 ,  0.03222245,
         0.04169602,  0.03958235,  0.02812612,  0.03541983,  0.02734712],
       [ 0.17134446,  0.5430228 ,  0.66477701,  0.02135648,  0.53482387,
         0.69206493,  0.65698254,  0.46683358,  0.58789355,  0.45390379],
       [ 0.1811465 ,  0.57408729,  0.70280665,  0.02257821,  0.56541933,
         0.73165562,  0.69456628,  0.49353955,  0.62152494,  0.47987009],
       [ 0.16890088,  0.53527864,  0.65529648,  0.02105191,  0.52719663,
         0.68219525,  0.64761317,  0.46017597,  0.57950947,  0.44743058],
       [ 0.18644922,  0.59089262,  0.72338   ,  0.02323915,  0.58197092,
         0.75307346,  0.71489841,  0.50798699

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [284]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a * phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [285]:
x = np.asarray([[1.0,0.0,3.0,8.0],
               [2.0,0.0,1.0,1.0],
               [1.5,2.5,1.0,0.0]])
n = 4
m = np.logical_and.reduce(np.mod(x,1) == 0, axis=-1)
m &= (x.sum(axis=-1) == n)
print(x[m])

[[ 2.  0.  1.  1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
x = np.random.randn(100)
n = 1000
idx = np.random